services:
  accounts:
    image: tnydevdocs/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tnydevdocs
  loans:
    image: tnydevdocs/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tnydevdocs
  cards:
    image: tnydevdocs/cards:s4
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tnydevdocs
networks:
    tnydevdocs:
        driver: bridge